### ISSUE TITLE
pb configuring the editor

### ISSUE THREAD

**Issue by stegarcia** [metadata101/iso19139.dgiwg#1]
The metadata/editor/schemaConfig is not present anymore in the 3.2.x branch nor in the 3.4+ versions of Geonetwork.

**Comment by etj** [comment]
Is this an issue related to the dgiwg schema plugin? Do you have an error installing or using it in a vanilla GN?

**Comment by stegarcia** [comment]
In fact my post was wrong, I managed to run the 3.2.x version of Geonetwork and the metadata/MetadataEditorConfiguration is present.

**Comment by stegarcia** [comment]
You can close the issue, it works fine. Thank you
